server:
    port: 8082
recursos:
    recurso1: valor del recurso 1
    recurso2: valor del recurso 2
    recurso3: valor del recurso 3
    recurso4: valor del recurso 4
    recurso5: valor del recurso 5
management:
    endpoints:
        web:
            exposure:
                include: '*'
                exclude: beans,env